[workspace]

[package]
name = "nirmana_solitaire_cmd"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 2
lto = "thin"
debug = "line-tables-only"

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false

[profile.debugging]
inherits = "dev"
debug = true

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
nirmana_solitaire = { path = "lib", features = ["std"] }
